global:
  resolve_timeout: 5m
  smtp_from: 'OCP Prometheus <ocp-dev@semperti>'
  smtp_smarthost: smtp-relay.semperti.com:25
  smtp_hello: smtp-relay.semperti.com
  smtp_require_tls: false
receivers:
- name: team_ocpadmin_email
  email_configs:
    - to: ocpadmin@semperti.com
- name: team_devops_email
  email_configs:
    - to: devops@semperti.com
- name: team_app1_email
  email_configs:
    - to: teamapp1@semperti.com
- name: team_app2_email
  email_configs:
    - to: teamapp2@semperti.com
- name: null
route:
  group_by: ['alertname', 'cluster', 'service']
  group_interval: 5m
  group_wait: 30s
  repeat_interval: 12h
  receiver: null
  routes:
  - match:
      alertname: Watchdog
    receiver: team_ocpadmin_email
  - match_re:
      namespace: ^(openshift|kube)$
    receiver: team_ocpadmin_email
  - match_re:
      alertname: ^(Cluster|Cloud|Machine|Pod|Kube|MCD|Alertmanager|etcd|TargetDown|CPU|Node|Clock|Prometheus|Failing|Network|IPTable)$
    receiver: team_ocpadmin_email
  - match:
      severity: critical
    receiver: team_ocpadmin_email
  - match_re:
      namespace: ^(app1-dev|app1-test|app1-homo)$
    receiver: team_app1_email
  - match_re:
      namespace: ^(app2-dev|app2-test|app2-homo)$
    receiver: team_app2_email